from django.urls import path
from baseApp import views


urlpatterns = [
    path(
        "ttd_admin_login/ttd_admin_homepage",
        views.ttd_admin_homepage,
        name="ttd_admin_homepage",
    ),
    path("ttd_admin_login/", views.ttd_admin_login, name="ttd_admin_login"),
    path("ttd_admin_signin/", views.ttd_admin_signin, name="ttd_admin_signin"),
    path("get_paragraph", views.get_paragraph, name="get_paragraph"),
    path("typing_tests", views.typing_tests, name="typing_tests"),
    path("get_typing_tests", views.get_typing_tests, name="get_typing_tests"),
    path("delete_paragraphs", views.delete_paragraphs, name="delete_paragraphs"),
    path("get_typing_variants", views.get_typing_variants, name="get_typing_variants"),
    path("delete_variants", views.delete_variants, name="delete_variants"),
    path("getUsers", views.getUsers, name="getUsers"),
    path("editing_tests", views.editing_tests, name="editing_tests"),
    path("getSearch", views.getSearch, name="getSearch"),
    path("getPlayerData", views.getPlayerData, name="getPlayerData"),
    path("startFrontend", views.startFrontend, name="startFrontend"),
    path("getFontendCodes", views.getFontendCodes, name="getFontendCodes"),
    path("setEventEnd", views.setEventEnd, name="setEventEnd"),
    path("setEventNext", views.setEventNext, name="setEventNext"),
    path("startTimerOne", views.startTimerOne, name="startTimerOne"),
    path("startTimerTwo", views.startTimerTwo, name="startTimerTwo"),
    path("rewardData", views.rewardData, name="srewardData"),
    path("getParterns", views.getParterns, name="getParterns"),
    path("getParternsHistory", views.getParternsHistory, name="getParternsHistory"),
    path("getParterns2", views.getParterns2, name="getParterns2"),
    path("getAllUserParterns", views.getAllUserParterns, name="getAllUserParterns"),
    path(
        "getStartTimerOneCodes",
        views.getStartTimerOneCodes,
        name="getStartTimerOneCodes",
    ),
    path("getStartTimerTwoCodes", views.getStartTimerTwoCodes, name="getStartTimerTwoCodes"),
    path("startLeaderBoard", views.startLeaderBoard, name="startLeaderBoard"),
    path("getLeaderBoardCode", views.getLeaderBoardCode, name="getLeaderBoardCode"),
    path("startTypingArea", views.startTypingArea, name="startTypingArea"),
    path("getTypingAreaCode", views.getTypingAreaCode, name="getTypingAreaCode"),
    path("getEvent1Code", views.getEvent1Code, name="getEvent1Code"),
    path("getEvent2Code", views.getEvent2Code, name="getEvent2Code"),
    path("starEvent1", views.starEvent1, name="starEvent1"),
    path("starEvent2", views.starEvent2, name="starEvent2"),
    path("get_concern", views.get_concern, name="get_concern"),
    path("get_concern3", views.get_concern3, name="get_concern3"),
    path("get_remaining_time", views.get_remaining_time, name="get_remaining_time"),
    path("get_stating_time", views.get_stating_time, name="get_stating_time"),
    path("getSubscription", views.getSubscription, name="getSubscription"),
    path("setSubscriptionPrice", views.setSubscriptionPrice, name="setSubscriptionPrice"),
    path("get_subscribers", views.get_subscribers, name="get_subscribers"),
    path("getTicketsPrices", views.getTicketsPrices, name="getTicketsPrices"),
    path("setTicketsPrice", views.setTicketsPrice, name="setTicketsPrice"),
    path("getTickets", views.getTickets, name="getTickets"),
    path("getTicketsSeach", views.getTicketsSeach, name="getTicketsSeach"),
    path("subsubscriberSerch", views.subsubscriberSerch, name="subsubscriberSerch"),
    path("getTicketsubscriPrices", views.getTicketsubscriPrices, name="getTicketsubscriPrices"),
    path("setLimitation", views.setLimitation, name="setLimitation"),
    path("getLimitations", views.getLimitations, name="getLimitations"),
    path("setMonetry", views.setMonetry, name="setMonetry"),
    path("deleteMotey", views.deleteMotey, name="deleteMotey"),
    path("deleteQuest", views.deleteQuest, name="deleteQuest"),
    path("setQuest", views.setQuest, name="setQuest"),
    path("setMask", views.setMask, name="setMask"),
]
