# Generated by Django 4.1.7 on 2023-04-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
