# Generated by Django 4.1.7 on 2023-04-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0002_alter_player_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
