# Generated by Django 4.1.7 on 2023-04-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0004_delete_player2_player_firstname_player_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='firstname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
