# Generated by Django 4.1.7 on 2023-04-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0005_alter_player_firstname_alter_player_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='mail',
            field=models.CharField(default='', max_length=255),
        ),
    ]
