# Generated by Django 4.1.7 on 2023-04-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0006_alter_player_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id2', models.CharField(max_length=10)),
                ('username2', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
