# Generated by Django 4.1.7 on 2023-04-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0009_typingdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typingdetails',
            name='cpm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='typingdetails',
            name='mistakes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='typingdetails',
            name='wpm',
            field=models.IntegerField(default=0),
        ),
    ]
