# Generated by Django 4.2 on 2023-05-25 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topApp", "0018_typingdetailshistory_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typingdetailshistory",
            name="date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
