# Generated by Django 4.2.3 on 2023-08-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0019_alter_typingdetailshistory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
