# Generated by Django 4.2.3 on 2023-08-05 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0023_alter_player_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
