# Generated by Django 4.2.3 on 2023-08-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0025_alter_player_date_alter_typingdetails_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_id', models.IntegerField(default=0)),
                ('tickets_purchased', models.IntegerField(default=0)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_available', models.IntegerField(default=0)),
                ('tickets_id', models.IntegerField(default=0)),
                ('tickets_used', models.IntegerField(default=0)),
            ],
        ),
    ]
