# Generated by Django 4.2.3 on 2023-08-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0026_ticketpurchase_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='tickets_available',
            field=models.IntegerField(default=1),
        ),
    ]
