# Generated by Django 4.2.3 on 2023-08-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0027_alter_tickets_tickets_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
    ]
