# Generated by Django 4.2.3 on 2023-08-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0028_ticketpurchase_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
