# Generated by Django 4.2.3 on 2023-09-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0029_ticketpurchase_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='amount_of_comments',
        ),
        migrations.AddField(
            model_name='player',
            name='account',
            field=models.CharField(default='new', max_length=20),
        ),
    ]
