# Generated by Django 4.2.3 on 2023-09-09 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0031_player_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('wpm', models.IntegerField()),
                ('cpm', models.IntegerField()),
                ('mistakes', models.IntegerField()),
                ('play_id', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=255)),
                ('typo_id', models.IntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
