# Generated by Django 4.2.3 on 2023-09-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0033_alter_player_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='statuss',
            field=models.CharField(default='', max_length=25),
        ),
    ]
