# Generated by Django 4.2.3 on 2023-09-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0034_player_statuss'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='claim_tickets',
            field=models.IntegerField(default=0),
        ),
    ]
