# Generated by Django 4.2.3 on 2023-09-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0035_tickets_claim_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('notification_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
