# Generated by Django 4.2.3 on 2023-09-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0036_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notf_id',
            field=models.IntegerField(default=0),
        ),
    ]
