# Generated by Django 4.2.3 on 2023-09-22 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0037_notification_notf_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
