# Generated by Django 4.2.3 on 2023-09-22 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0038_alter_notification_notification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
