# Generated by Django 4.2.3 on 2023-09-25 03:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0039_comments_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('source_text', models.CharField(max_length=5000)),
                ('reply', models.CharField(default='no', max_length=50)),
                ('source_id', models.IntegerField(default=0)),
                ('text_id', models.IntegerField(default=0)),
                ('source_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='ticketpurchase',
            name='purchase_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
