# Generated by Django 4.2.3 on 2023-10-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('topApp', '0042_subscription_subscriptiondate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='player_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='player',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='player',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='player_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
