# Generated by Django 4.2.3 on 2023-10-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0043_player_groups_player_is_superuser_player_last_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typing_parttern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ascending_parttern', models.CharField(default='', max_length=99999)),
                ('deascending_parttern', models.CharField(default='', max_length=99999)),
                ('keyStroke_parttern', models.CharField(default='', max_length=99999)),
                ('finished_parttern', models.CharField(default='', max_length=99999)),
                ('given_words', models.CharField(default='', max_length=99999)),
                ('wpm', models.IntegerField(default=0)),
                ('cpm', models.IntegerField(default=0)),
                ('mistakes', models.IntegerField(default=0)),
                ('verification_token', models.CharField(default='', max_length=99)),
            ],
        ),
    ]
