# Generated by Django 4.2.3 on 2023-10-25 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0044_typing_parttern'),
    ]

    operations = [
        migrations.AddField(
            model_name='typing_parttern',
            name='Date_partten',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
