# Generated by Django 4.2.3 on 2023-10-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0045_typing_parttern_date_partten'),
    ]

    operations = [
        migrations.AddField(
            model_name='typing_parttern',
            name='partern_id',
            field=models.IntegerField(default=0),
        ),
    ]
