# Generated by Django 4.2.3 on 2023-10-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0047_alter_typing_parttern_partern_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='typing_parttern',
            name='pt_name',
            field=models.CharField(default='', max_length=99),
        ),
    ]
