# Generated by Django 4.2.3 on 2023-10-25 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0048_typing_parttern_pt_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typing_partterns_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partern_id', models.IntegerField()),
                ('ascending_parttern', models.CharField(default='', max_length=99999)),
                ('deascending_parttern', models.CharField(default='', max_length=99999)),
                ('pt_name', models.CharField(default='', max_length=99)),
                ('keyStroke_parttern', models.CharField(default='', max_length=99999)),
                ('finished_parttern', models.CharField(default='', max_length=99999)),
                ('given_words', models.CharField(default='', max_length=99999)),
                ('wpm', models.IntegerField(default=0)),
                ('cpm', models.IntegerField(default=0)),
                ('mistakes', models.IntegerField(default=0)),
                ('verification_token', models.CharField(default='', max_length=99)),
                ('Date_partten', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
