# Generated by Django 4.2.3 on 2023-10-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0049_typing_partterns_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_token', models.CharField(default='', max_length=99)),
            ],
        ),
    ]
