# Generated by Django 4.2.3 on 2023-10-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0050_verificationtokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bloked',
            field=models.CharField(default='no', max_length=100),
        ),
    ]
