# Generated by Django 4.2.3 on 2023-10-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0051_player_bloked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='bloked',
            new_name='blocked',
        ),
    ]
