# Generated by Django 4.1.7 on 2023-04-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('v_code', models.IntegerField()),
                ('os', models.CharField(max_length=100)),
            ],
        ),
    ]
