# Generated by Django 4.1.7 on 2023-04-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0003_player2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player2',
        ),
        migrations.AddField(
            model_name='player',
            name='firstname',
            field=models.CharField(default='firstname', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='lastname',
            field=models.CharField(default='lastname', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='mail',
            field=models.CharField(default='mail', max_length=255),
        ),
    ]
