# Generated by Django 4.1.7 on 2023-04-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0007_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='amount_of_comments',
            field=models.IntegerField(default=0),
        ),
    ]
