# Generated by Django 4.1.7 on 2023-04-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0008_player_amount_of_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpm', models.IntegerField()),
                ('cpm', models.IntegerField()),
                ('mistakes', models.IntegerField()),
                ('play_id', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
            ],
        ),
    ]
