# Generated by Django 4.1.7 on 2023-04-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0010_alter_typingdetails_cpm_alter_typingdetails_mistakes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typingdetails',
            name='cpm',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='typingdetails',
            name='mistakes',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='typingdetails',
            name='wpm',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
