# Generated by Django 4.1.7 on 2023-05-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topApp', '0012_alter_typingdetails_cpm_alter_typingdetails_mistakes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typingdetails',
            name='cpm',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='typingdetails',
            name='mistakes',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='typingdetails',
            name='play_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='typingdetails',
            name='wpm',
            field=models.CharField(max_length=10),
        ),
    ]
