# Generated by Django 4.2 on 2023-05-07 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topApp", "0016_typingdetails_typo_id_typingdetailshistory_typo_id2"),
    ]

    operations = [
        migrations.AddField(
            model_name="typingdetails",
            name="date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
