# Generated by Django 4.2 on 2023-05-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topApp", "0017_typingdetails_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="typingdetailshistory",
            name="date",
            field=models.CharField(default="", max_length=255),
        ),
    ]
