# Generated by Django 4.1.7 on 2023-04-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('passw', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('emails', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aunthaticate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_code', models.CharField(max_length=50)),
            ],
        ),
    ]
