# Generated by Django 4.2 on 2023-05-30 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baseApp", "0002_typing_testing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="typing_testing",
            name="amount_of_words",
        ),
        migrations.RemoveField(
            model_name="typing_testing",
            name="time_given",
        ),
    ]
