# Generated by Django 4.2.3 on 2023-07-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_variant_paragraphs_variant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typing_testing',
            name='test_name',
        ),
        migrations.RemoveField(
            model_name='typing_testing',
            name='test_type',
        ),
    ]
