# Generated by Django 4.2.3 on 2023-08-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0006_remove_typing_testing_test_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frontend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FrontendId', models.IntegerField(default=5747)),
            ],
        ),
    ]
