# Generated by Django 4.2.3 on 2023-08-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0007_frontend'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endEvent', models.IntegerField(default=0)),
            ],
        ),
    ]
