# Generated by Django 4.2.3 on 2023-08-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0008_endevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='endevent',
            name='endEventId',
            field=models.IntegerField(default=5747),
        ),
    ]
