# Generated by Django 4.2.3 on 2023-08-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0011_ticketpurchase_tickets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketPurchase',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
