# Generated by Django 4.2.3 on 2023-09-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0014_typingarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins_details',
            name='admin_id',
            field=models.IntegerField(default=57473172877),
        ),
    ]
