# Generated by Django 4.2.3 on 2023-09-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0016_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Event1',
        ),
    ]
