# Generated by Django 4.2.3 on 2023-09-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0020_alter_countdown_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='expiration_time',
            field=models.DateTimeField(),
        ),
    ]
