# Generated by Django 4.2.3 on 2023-09-30 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0021_alter_countdown_expiration_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endevent',
            name='endEvent',
        ),
    ]
