# Generated by Django 4.2.3 on 2023-09-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0022_remove_endevent_endevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countdown2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.DateTimeField()),
            ],
        ),
    ]
