# Generated by Django 4.2.3 on 2023-10-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0025_textbehaviour'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newPrice', models.IntegerField(default=14999)),
                ('oldPrice', models.IntegerField(default=22969)),
                ('dropBy', models.IntegerField(default=17)),
            ],
        ),
    ]
