# Generated by Django 4.2.3 on 2023-10-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0026_subscriptionprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('newPrice', models.IntegerField(default=0)),
                ('oldPrice', models.IntegerField(default=0)),
                ('dropBy', models.IntegerField(default=0)),
            ],
        ),
    ]
