# Generated by Django 4.2.3 on 2023-10-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0027_ticketprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerAndLooserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messagesx', models.CharField(max_length=1000)),
                ('messageId', models.CharField(max_length=20)),
            ],
        ),
    ]
