# Generated by Django 4.2.3 on 2023-10-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0028_winnerandloosermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limiter_name', models.CharField(default='', max_length=255)),
                ('limiter', models.IntegerField(default=0)),
            ],
        ),
    ]
