# Generated by Django 4.2.3 on 2023-10-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0029_controlresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monetary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('des1', models.CharField(default='', max_length=255)),
                ('des2', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('des1', models.CharField(default='', max_length=255)),
                ('des2', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
