# Generated by Django 4.2.3 on 2023-10-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0032_remove_quest_des1_remove_quest_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aunthaticate',
            name='aunth_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
