# Generated by Django 4.2.3 on 2023-10-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0033_aunthaticate_aunth_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionprice',
            name='tkts',
            field=models.IntegerField(default=20),
        ),
    ]
