# Generated by Django 4.2.3 on 2023-10-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0034_subscriptionprice_tkts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('eventId', models.IntegerField(default=0)),
            ],
        ),
    ]
