# Generated by Django 4.2 on 2023-05-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Typing_testing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test", models.CharField(max_length=1000000)),
                ("test_name", models.CharField(max_length=1000000)),
                ("test_type", models.CharField(max_length=1000000)),
                ("amount_of_words", models.IntegerField()),
                ("time_given", models.IntegerField()),
                ("test_id", models.IntegerField()),
            ],
        ),
    ]
