# Generated by Django 4.2 on 2023-05-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseApp", "0003_remove_typing_testing_amount_of_words_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Variant_paragraphs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variant_p", models.CharField(default="", max_length=1000000)),
            ],
        ),
    ]
